### PR TITLE
Adding controller

### LINKED ISSUE #98: Adding controllers,main.java and updating canvas fxml file
Whiteboard controller handles transition from Startsession fxml to canvas fxml
adding canvas controller which handles operations being done inside canvas fxml page.
Adding main.java file
updating canvas fxml to include menu items and shape items

### PR DESCRIPTION
**Pull request by sai-deekshith16**
Closes convict-git/KoraKaagaz#98

### CODE REVIEW

**Comment by convict-git** [comment]
The new PR is a bit untidy. I can't merge it. 
I'll suggest continuing the work on it (write more code), review it properly at L2 and keep merging to AddingController so that this PR gets updated.

**Comment by muhammedyaseen-git** [comment]
@sai-deekshith16 what is the update on this PR?

**Comment by convict-git** [comment]
@sai-deekshith16 Please update with the status of this PR. Also, it doesn't look like the team is using git properly. Why are there just merge commits? Is the git guidelines not followed within the team?

**Comment by sai-deekshith16** [comment]
This PR can be closed as I included the same files with few changes in the latest PR "Complete UI Module". You can refer the commits in that PR.

**Pull request closed without merging**
