### PR TITLE
Resource leak

### LINKED ISSUE #131: Resource leak through sockets
https://github.com/convict-git/KoraKaagaz/blob/3bdb85cbeeed067cca73c7684d02aad5b90a2cf5/src/networking/CommunicatorFactory.java#L150

https://github.com/convict-git/KoraKaagaz/blob/3bdb85cbeeed067cca73c7684d02aad5b90a2cf5/src/networking/server/ServerManager.java#L38

@sravand123 @Prudhvis-gitrepo How are we going to release the sockets?

### PR DESCRIPTION
**Pull request by sravand123**
Closes #131

### CODE REVIEW

**Comment by convict-git** [comment]
@Prudhvis-gitrepo @sravand123 What about the socket in ServerManager.java?

**Comment by sravand123** [comment]
> @Prudhvis-gitrepo @sravand123 What about the socket in ServerManager.java?

@convict-git I found no way to close socket in serverManager .. as it in infinite loop.. if we try to close socket after while loop it is throwing code unreachable error

**Comment by Prudhvis-gitrepo** [comment]
> @Prudhvis-gitrepo @sravand123 What about the socket in ServerManager.java
I'm not the author of ServerManager.java mentioning me is inappropriate.

**Comment by convict-git** [comment]
@sravand123 Please open a new issue for the socket in ServerManager.java. 
You may not fix it now but it will be good for future reference.

Merging.

**Review by convict-git — APPROVED** [review]

**Pull request merged**
