### PR TITLE
Networking Module over LAN 

### LINKED ISSUE #39: Adding Queue Interface - Networking Module - 111701021 - Shiva Santhosh
Adding the queue interface.

### LINKED ISSUE #43: Adding OutgoingPacket Class - Networking Module - Shiva Santhosh - 111701021
I have implemented the outgoingPacket class which is used by the Send and SendQueueListener component of the networking module. This class is used to store/retrieve the data in the queue and this class will fix the structure of the data b/w the components so they know how to add and retrieve the data from the queue.

### LINKED ISSUE #45: Adding IncomingPacket Class - 111701021 - Shiva Santhosh
I have implemented the incomingPacket class which is used by the SocketListener and RecieveQueueListener component of the networking module. This class is used to store/retrieve the data in the queue and this class will fix the structure of the data b/w the components so they know how to add and retrieve the data from the queue.

### LINKED ISSUE #46: SendQueueListener Implemenation.
The sendQueueListener will do the task of taking the outgoing packets from send queue and then the messages will be transmitted over the network using sockets.

### LINKED ISSUE #48: Adding the Queue Class and some small changes to do- Networking Module - Shiva Santhosh - 111701021
This issue is created for implementing the queue class which is blocking in nature and also thread-safe. This class is the implementation of the interface IQueue.java. I have also fix some minor bugs in my previous implementations

### LINKED ISSUE #50: Add the LanCommunicator class ( Start , Stop, Send ) - Networking Module - 111701017
This class instance will be created by LanCommunicatorFactory by giving port number (on which we will be listening for messages) for the constructor.

In Start method, we will be starting the communication on the network

Three queues will be created : 
1. Send Queue ( which contains the message that needs to be send on the network )
2. Receive Queue for Processing ( which contains the messages that we received from the network for the processing module )
3. Receive Queue for Content ( which contains the messages that we received from the network for the content module )

  Four Threads will be created : 
1. Send Queue Listener ( which takes messages from the send queues and sends on the network )
2. Socket Listener ( which listens on a socket and sends the messages received from the network to the respective receive queues based on the identifier )
3. Receive Queue Listener for Processing ( which takes messages from the processing receive queue and sends it through the handler )
4. Receive Queue Listener for Content ( which takes messages from the content receive queue and sends it through its handler )

In Stop method,
Basically communication will be stopped in this method, all the threads and instances will be stopped and made null.

In Send method, 
Processing and Content module will be using this method with destination, message and identifier as arguments. A object will be created with this arguments and pushed into the queue and later will be sent through the network handled by the Send Queue listener.

### LINKED ISSUE #52: Add Socket Listener - Networking Module
Overview:
This class will keep listening for client requests for data transfer using sockets, when it finds one it connects with it and receive the data through the socket and then pushes the data received into content module queue or processing module queue based on the identifier received.
Implementation Details:
This class implements runnable so it has a run method which is where the most of the logic is implemented and some utility methods to parse the received data.

### LINKED ISSUE #62: Networking module- CommunicatorFactory class - 111701023

### LINKED ISSUE #63: Networking Module - add requested feature of communicatorfactory class - 111701023
New communicatorfactory class is designed to give client's private ip or local ip address

### LINKED ISSUE #66: NetworkingModule- ReceiveQueueListener class
Class 'ReceiveQueueListener' implements runnable interface, helps in dequeuing the receiving queue and calling handler method
  of the corresponding module ( either processing module or content module) by passing the message.

### LINKED ISSUE #79: full Communicator Factory class with giving ip and port
Tried to implement the new feature with in the short period of time.

### LINKED ISSUE #81: Add ClientInfo class

### LINKED ISSUE #82: add subscribeForNotifications method to LanCommunicator class

### PR DESCRIPTION
**Pull request by sravand123**
This is the complete Implementation of Network module over local area Network (LAN)
Closes #82 - src/networking/LanCommunicator.java
Closes #81 - src/networking/utility/ClientInfo.java 
Closes #79 - src/networking/CommunicatorFactory.java 
Closes #43 - src/networking/utility/IncomingPacket.java
Closes #62 - src/networking/CommunicatorFactory.java
Closes #63 - src/networking/CommunicatorFactory.java  src/networking/utility/ClientInfo.java
Closes #66 - src/networking/ReceiveQueueListener.java
Closes #50 - src/networking/LanCommunicator.java
Closes #52 - src/networking/SocketListener.java 
Closes #45 - src/networking/OutgoingPacket.java 
Closes #46 - src/networking/SendQueueListener.java
Closes #48 - src /networking/ConcurrentBlockingQueue 
Closes #39 -src/networking/IQueue.java

### CODE REVIEW

**Comment by muhammedyaseen-git** [comment]
There are quite a good number of spelling mistakes across comments which can be easily rectified in the IDE. Also, there is a mention on the datagram socket's importance in the code, but I feel it is better not to put the merits or demerits in the code as the spec already contains it. I have also commented on an issue for a clarity on some line. The rest of the code looks fine, let us see @convict-git review for a better clarity.

Good work team!

**Comment by convict-git** [comment]
Will send some change requests by today. @muhammedyaseen-git @sravand123

**Comment by convict-git** [comment]
@sravand123 You need to send a new PR. This PR contains old merged commits as well (For docs and interfaces). Seems like you didn't sync the master first.

**Comment by sravand123** [comment]
> @sravand123 You need to send a new PR. This PR contains old merged commits as well (For docs and interfaces). Seems like you didn't sync the master first.

Sure will do it

**Pull request closed without merging**
